services:
  - type: web
    name: team-tasks-api
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'npm start'
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DB_FILE
        value: /tmp/data.sqlite
      - key: SEED
        value: 'false'
    